### ISSUE TITLE
vagrant up --provider virtualbox

### ISSUE THREAD

**Issue by gitttt** [eurecom-s3/vagrant#1]
One could add to the readme that vagrant up has to be appended by `--provider virtualbox`.
Just to avoid problems.

For example, a `vagrant up` only causes an error for people having the vmware plugin installed as vagrant then default to provider `vmware-workstation`

**Comment by aurelf** [comment]
Is there a good reason why it does not work with vmware ?

**Comment by gitttt** [comment]
No, it is just that the base box is for Virtualbox. This is fine as long as you either don't have the VMware vagrant plugin installed or if you add the above parameter.

**Comment by aurelf** [comment]
This was fixed in ea44161bc3284e6680102a2ae57667a9a225148e
